### ISSUE TITLE
CSI controller error in csi-error`

### ISSUE THREAD

**Issue by itsbanjo** [sa-ne/openshift4-vmware-upi#2]
I'm getting this error after the vsi-controller-deployment:

main.go:72] failed to check if plugin supports node resize: error getting node capabilities: rpc error: code = Unimplemented desc = unknown service csi.v1.Node.

One of the github pages suggested that the resizer is disabled. So, should be deprecated from the 1-vsphere-csi-controller-deployment.yaml

https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/250

**Comment by nasx** [comment]
@itsbanjo sorry just noticed you submitted this issue. I've been testing against vSphere 7 where I believe this is supported. I'll make a note in the README.md though for 6.5/6.7, thanks!
